services:
  - type: web
    name: lettre-motivation-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: web_app.py
    plan: free
    healthCheckPath: /health
    autoDeploy: true
