services:
  - type: web
    name: lettre-motivation-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn test:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free
    healthCheckPath: /health
    autoDeploy: true
