services:
  - type: web
    name: lettre-motivation-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MODEL_PATH
        sync: false
      - key: FLASK_ENV
        value: production
    plan: free
    healthCheckPath: /health
    autoDeploy: true
