services:
  - type: web
    name: lettre-motivation-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MODEL_PATH
        sync: false
    plan: free
    healthCheckPath: /health
    autoDeploy: true
